####################################################################
####################################################################
####################################################################
#██    ██ ██    ██ ██      ██ ███    ███  █████  ██ ████████ ███████
#██    ██ ██    ██ ██      ██ ████  ████ ██   ██ ██    ██    ██
#██    ██ ██    ██ ██      ██ ██ ████ ██ ███████ ██    ██    █████
#██  ██   ██  ██  ██      ██ ██  ██  ██ ██   ██ ██    ██    ██
#████     ████   ███████ ██ ██      ██ ██   ██ ██    ██    ███████
####################################################################
####################################################################
####################################################################

#This Plugin is from EliVB

#This is a Plugin like DonutSMP Settings, you can change all of the messages.
#For more Premium Skripts or Plugins join our Discord: "https://discord.gg/V3fcWZrccj"

#permissions
#settings.reload

#Plugin Placeholders
#%status%
#%sound%
#%time%

settings-gui:
  title: "&8ѕᴇᴛᴛɪɴɢѕ"
  gui-slots: 36

  #Fill-Material Settings
  fill:
    enabled: false
    material: "BLACK_STAINED_GLASS_PANE"
    display-name:
    sound: "ENTITY_VILLAGER_NO"
    slots: "0-8,27-35"

  cooldown:
    enabled: false
    duration: 3

  #You can´t change this
  status:
    on: "&#00FF00&lON"
    off: "&x&F&9&1&8&1&8&lOFF"

  #You can add or change settings here if you need them
  items:
    public_chat:
      slot: 0
      material: "OAK_SIGN"
      display-name: "&#08FB7Bᴘᴜʙʟɪᴄ ᴄʜᴀᴛ"
      lore: "&fCurrently: %status%"
      command: "togglechat" #Soon, a Plugin come for this feature
      default: true
    private_messages:
      slot: 1
      material: "DARK_OAK_SIGN"
      display-name: "&#08FB7Bᴘʀɪᴠᴀᴛᴇ ᴍᴇssᴀɢᴇs"
      lore: "&fCurrently: %status%"
      command: "msgtoggle" #Soon, a Plugin come for this feature
      default: true
    chat_server_messages:
      slot: 2
      material: "WARPED_SIGN"
      display-name: "&#08FB7Bᴄʜᴀᴛ sᴇʀᴠᴇʀ ᴍᴇssᴀɢᴇs"
      lore: "&fCurrently: %status%"
      command: "servertoggle" #Soon, a Plugin come for this feature
      default: true
    hotbar_server_messages:
      slot: 3
      material: "CRIMSON_SIGN"
      display-name: "&#08FB7Bʜᴏᴛʙᴀʀ sᴇʀᴠᴇʀ ᴍᴇssᴀɢᴇs"
      lore: "&fCurrently: %status%"
      command: "hotbartoggle" #Soon, a Plugin come for this feature
      default: true
    pay_alerts:
      slot: 4
      material: "CHERRY_SIGN"
      display-name: "&#08FB7Bᴘᴀʏ ᴀʟᴇʀᴛs"
      lore: "&fCurrently: %status%"
      command: "paytoggle" #Soon, a Plugin come for this feature
      default: true
    bounty_alerts:
      slot: 5
      material: "BAMBOO_SIGN"
      display-name: "&#08FB7Bʙᴏᴜɴᴛʏ ᴀʟᴇʀᴛs"
      lore: "&fCurrently: %status%"
      command: "bountytoggle" #Soon, a Plugin come for this feature
      default: true
    auction_alerts:
      slot: 6
      material: "ACACIA_SIGN"
      display-name: "&#08FB7Bᴀᴜᴄᴛɪᴏɴ ᴀʟᴇʀᴛs"
      lore: "&fCurrently: %status%"
      command: "auctiontoggle" #Soon, a Plugin come for this feature
      default: true
    fast_crystals:
      slot: 9
      material: "END_CRYSTAL"
      display-name: "&#08FB7Bғᴀsᴛ ᴄʀʏsᴛᴀʟs"
      lore: "&fCurrently: %status%"
      command: "fastercrystals" #Soon, a Plugin come for this feature
      default: false
    totem_particles:
      slot: 10
      material: "TOTEM_OF_UNDYING"
      display-name: "&#08FB7Bᴛᴏᴛᴇᴍ ᴘᴀʀᴛɪᴄʟᴇs"
      lore: "&fCurrently: %status%"
      command: "totemtoggle" #Soon, a Plugin come for this feature
      default: true
    explosion_particles:
      slot: 11
      material: "TNT"
      display-name: "&#08FB7Bᴇxᴘʟᴏsɪᴏɴ ᴘᴀʀᴛɪᴄʟᴇs"
      lore: "&fCurrently: %status%"
      command: "explosiontoggle" #Soon, a Plugin come for this feature
      default: true
    explosion_sounds:
      slot: 12
      material: "GOAT_HORN"
      display-name: "&#08FB7Bᴇxᴘʟᴏsɪᴏɴ sᴏᴜɴᴅs"
      lore: "&fCurrently: %status%"
      command: "explosionsoundtoggle" #Soon, a Plugin come for this feature
      default: true
    quick_auction_buy:
      slot: 13
      material: "GOLD_INGOT"
      display-name: "&#08FB7Bǫᴜɪᴄᴋ ᴀᴜᴄᴛɪᴏɴ ʙᴜʏ"
      lore: "&fCurrently: %status%"
      command: "quickbuy" #Soon, a Plugin come for this feature
      default: false
    chainmail_on_respawn:
      slot: 14
      material: "CHAINMAIL_HELMET"
      display-name: "&#08FB7Bᴄʜᴀɪɴᴍᴀɪʟ ᴏɴ ʀᴇsᴘᴀᴡɴ"
      lore: "&fCurrently: %status%"
      command: "chainmailrespawn" #Soon, a Plugin come for this feature
      default: true
    disable_mob_spawns:
      slot: 15
      material: "ZOMBIE_HEAD"
      display-name: "&#08FB7Bᴅɪsᴀʙʟᴇ ᴍᴏʙ sᴘᴀᴡɴs"
      lore: "&fCurrently: %status%"
      command: "mobspawntoggle" #Soon, a Plugin come for this feature
      default: true
    player_visibility:
      slot: 18
      material: "PLAYER_HEAD"
      display-name: "&#08FB7Bᴘʟᴀʏᴇʀ ᴠɪsɪʙɪʟɪᴛʏ"
      lore: "&fCurrently: %status%"
      command: "playertoggle" #Soon, a Plugin come for this feature
      default: true
    scoreboard:
      slot: 19
      material: "NAME_TAG"
      display-name: "&#08FB7Bsᴄᴏʀᴇʙᴏᴀʀᴅ"
      lore: "&fCurrently: %status%"
      command: "scoretoggle" #Soon, a Plugin come for this feature
      default: true
    tpa_confirm_menu:
      slot: 20
      material: "FEATHER"
      display-name: "&#08FB7Bᴛᴘᴀ ᴄᴏɴғɪʀᴍ ᴍᴇɴᴜ"
      lore: "&fCurrently: %status%"
      command: "tpaconfirmtoggle" #Soon, a Plugin come for this feature
      default: true
    sounds_notifications:
      slot: 21
      material: "NOTE_BLOCK"
      display-name: "&#08FB7Bsᴏᴜɴᴅs ɴᴏᴛɪғɪᴄᴀᴛɪᴏɴs"
      lore: "&fCurrently: %status%"
      command: "soundstoggle" #Soon, a Plugin come for this feature
      default: true
    order_notifications:
      slot: 22
      material: "MAP"
      display-name: "&#08FB7Bᴏʀᴅᴇʀ ɴᴏᴛɪғɪᴄᴀᴛɪᴏɴs"
      lore: "&fCurrently: %status%"
      command: "ordertoggle" #Soon, a Plugin come for this feature
      default: true
    duels_requests:
      slot: 23
      material: "DIAMOND_SWORD"
      display-name: "&#08FB7Bᴅᴜᴇʟs ʀᴇǫᴜᴇsᴛs"
      lore: "&fCurrently: %status%"
      command: "duelstoggle" #Soon, a Plugin come for this feature
      default: true
    tpa_requests:
      slot: 27
      material: "ENDER_PEARL"
      display-name: "&#08FB7Bᴛᴘᴀ ʀᴇǫᴜᴇsᴛs"
      lore: "&fCurrently: %status%"
      command: "tpatoggle" #Soon, a Plugin come for this feature
      default: true
    tpa_here_requests:
      slot: 28
      material: "ENDER_EYE"
      display-name: "&#08FB7Bᴛᴘᴀ ʜᴇʀᴇ ʀᴇǫᴜᴇsᴛs"
      lore: "&fCurrently: %status%"
      command: "tpaheretoggle" #Soon, a Plugin come for this feature
      default: true
    team_invites:
      slot: 29
      material: "SHIELD"
      display-name: "&#08FB7Bᴛᴇᴀᴍ ɪɴᴠɪᴛᴇs"
      lore: "&fCurrently: %status%"
      command: "teamtoggle" #Soon, a Plugin come for this feature
      default: true
    payments:
      slot: 30
      material: "EMERALD"
      display-name: "&#08FB7Bᴘᴀʏᴍᴇɴᴛs"
      lore: "&fCurrently: %status%"
      command: "paymenttoggle" #Soon, a Plugin come for this feature
      default: true
    team_chat:
      slot: 31
      material: "BELL"
      display-name: "&#08FB7Bᴛᴇᴀᴍ ᴄʜᴀᴛ"
      lore: "&fCurrently: %status%"
      command: "teamchattoggle" #Soon, a Plugin come for this feature
      default: true
    worth_display:
      slot: 32
      material: "LIME_CANDLE"
      display-name: "&#08FB7Bᴡᴏʀᴛʜ ᴅɪsᴘʟᴀʏ"
      lore: "&fCurrently: %status%"
      command: "worthtoggle" #For this feature, you need to install the Plugin "DonutSell" (https://www.spigotmc.org/resources/donutsell.129692/)
      default: true
    after_duel_songs:
      slot: 33
      material: "JUKEBOX"
      display-name: "&#08FB7Bᴀғᴛᴇʀ ᴅᴜᴇʟ sᴏɴɢs"
      lore: "&fCurrently: %status%"
      command: "duelsongtoggle" #Soon, a Plugin come for this feature
      default: true

sound:
  menu-click: "UI_BUTTON_CLICK"
  settings-reload: "ENTITY_PLAYER_LEVELUP"
  no-permission: "ENTITY_VILLAGER_NO"
  you-must-wait: "ENTITY_VILLAGER_NO"
