settings-gui:
  title: "&8ᴄÀɪ ᴆặᴛ"
  gui-slots: 36

  fill:
    enabled: false
    material: "BLACK_STAINED_GLASS_PANE"
    display-name:
    sound: "ENTITY_VILLAGER_NO"
    slots: "0-8,27-35"

  cooldown:
    enabled: false
    duration: 3

  status:
    on: "&#00FF00&lBẬT"
    off: "&x&F&9&1&8&1&8&lTẮT"

  items:
    public_chat:
      slot: 0
      material: "OAK_SIGN"
      display-name: "&#08FB7Bᴄʜᴀᴛ ᴄʜᴜɴɢ"
      lore: "&fHiện tại: %status%"
      command: "togglechat"
      default: true
    private_messages:
      slot: 1
      material: "DARK_OAK_SIGN"
      display-name: "&#08FB7Bᴛɪɴ ɴʜắɴ ʀɪêɴɢ"
      lore: "&fHiện tại: %status%"
      command: "msgtoggle"
      default: true
    chat_server_messages:
      slot: 2
      material: "WARPED_SIGN"
      display-name: "&#08FB7Bᴛʜôɴɢ ʙáᴏ ᴄʜᴀᴛ"
      lore: "&fHiện tại: %status%"
      command: "servertoggle"
      default: true
    hotbar_server_messages:
      slot: 3
      material: "CRIMSON_SIGN"
      display-name: "&#08FB7Bᴛʜôɴɢ ʙáᴏ ʜᴏᴛʙᴀʀ"
      lore: "&fHiện tại: %status%"
      command: "hotbartoggle"
      default: true
    pay_alerts:
      slot: 4
      material: "CHERRY_SIGN"
      display-name: "&#08FB7Bᴛʜôɴɢ ʙáᴏ ᴛʜᴀɴʜ ᴛᴏáɴ"
      lore: "&fHiện tại: %status%"
      command: "paytoggle"
      default: true
    bounty_alerts:
      slot: 5
      material: "BAMBOO_SIGN"
      display-name: "&#08FB7Bᴛʜôɴɢ ʙáᴏ ʙᴏᴜɴᴛʏ"
      lore: "&fHiện tại: %status%"
      command: "bountytoggle"
      default: true
    auction_alerts:
      slot: 6
      material: "ACACIA_SIGN"
      display-name: "&#08FB7Bᴛʜôɴɢ ʙáᴏ ᴆấᴜ ɢɪá"
      lore: "&fHiện tại: %status%"
      command: "auctiontoggle"
      default: true
    nightvision:
      slot: 9
      material: "TORCH"
      display-name: "&#08FB7Bɴʜìɴ ᴆêᴍ ᴠĩɴʜ ᴠɪễɴ"
      lore: "&fHiện tại: %status%"
      command: "nightvisiontoggle"
      default: false
    totem_particles:
      slot: 10
      material: "TOTEM_OF_UNDYING"
      display-name: "&#08FB7Bʜɪệᴜ ứɴɢ ᴛᴏᴛᴇᴍ"
      lore: "&fHiện tại: %status%"
      command: "totemtoggle"
      default: true
    explosion_particles:
      slot: 11
      material: "TNT"
      display-name: "&#08FB7Bʜɪệᴜ ứɴɢ ɴổ"
      lore: "&fHiện tại: %status%"
      command: "explosiontoggle"
      default: true
    explosion_sounds:
      slot: 12
      material: "GOAT_HORN"
      display-name: "&#08FB7Bâᴍ ᴛʜᴀɴʜ ɴổ"
      lore: "&fHiện tại: %status%"
      command: "explosionsoundtoggle"
      default: true
    quick_auction_buy:
      slot: 13
      material: "GOLD_INGOT"
      display-name: "&#08FB7Bᴍᴜᴀ ɴʜᴀɴʜ ᴆấᴜ ɢɪá"
      lore: "&fHiện tại: %status%"
      command: "quickbuy"
      default: false
    chainmail_on_respawn:
      slot: 14
      material: "CHAINMAIL_HELMET"
      display-name: "&#08FB7Bɢɪáᴘ ᴋʜɪ ʀᴇsᴘᴀᴡɴ"
      lore: "&fHiện tại: %status%"
      command: "chainmailrespawn"
      default: true
    disable_mob_spawns:
      slot: 15
      material: "ZOMBIE_HEAD"
      display-name: "&#08FB7Bắɴ ᴍᴏʙ sᴘᴀᴡɴ"
      lore: "&fHiện tại: %status%"
      command: "mobspawntoggle"
      default: true
    player_visibility:
      slot: 18
      material: "PLAYER_HEAD"
      display-name: "&#08FB7BʜɪệN ɴɢườɪ ᴄʜơɪ"
      lore: "&fHiện tại: %status%"
      command: "playertoggle"
      default: true
    scoreboard:
      slot: 19
      material: "NAME_TAG"
      display-name: "&#08FB7Bsᴄᴏʀᴇʙᴏᴀʀᴅ"
      lore: "&fHiện tại: %status%"
      command: "scoretoggle"
      default: true
    tpa_confirm_menu:
      slot: 20
      material: "FEATHER"
      display-name: "&#08FB7Bxáᴄ ɴʜậɴ ᴛᴘᴀ"
      lore: "&fHiện tại: %status%"
      command: "tpaconfirmtoggle"
      default: true
    sounds_notifications:
      slot: 21
      material: "NOTE_BLOCK"
      display-name: "&#08FB7Bâᴍ ᴛʜᴀɴʜ ᴛʜôɴɢ ʙáᴏ"
      lore: "&fHiện tại: %status%"
      command: "soundstoggle"
      default: true
    order_notifications:
      slot: 22
      material: "MAP"
      display-name: "&#08FB7Bᴛʜôɴɢ ʙáᴏ ᴆơɴ ʜàɴɢ"
      lore: "&fHiện tại: %status%"
      command: "ordertoggle"
      default: true
    duels_requests:
      slot: 23
      material: "DIAMOND_SWORD"
      display-name: "&#08FB7Bʏêᴜ ᴄầᴜ ᴅᴜᴇʟ"
      lore: "&fHiện tại: %status%"
      command: "duelstoggle"
      default: true
    tpa_requests:
      slot: 27
      material: "ENDER_PEARL"
      display-name: "&#08FB7Bʏêᴜ ᴄầᴜ ᴛᴘᴀ"
      lore: "&fHiện tại: %status%"
      command: "tpatoggle"
      default: true
    tpa_here_requests:
      slot: 28
      material: "ENDER_EYE"
      display-name: "&#08FB7Bʏêᴜ ᴄầᴜ ᴛᴘᴀ ʜᴇʀᴇ"
      lore: "&fHiện tại: %status%"
      command: "tpaheretoggle"
      default: true
    team_invites:
      slot: 29
      material: "SHIELD"
      display-name: "&#08FB7Bʟờɪ ᴍờɪ ᴛᴇᴀᴍ"
      lore: "&fHiện tại: %status%"
      command: "teamtoggle"
      default: true
    payments:
      slot: 30
      material: "EMERALD"
      display-name: "&#08FB7Bɴʜậɴ ᴛɪềɴ"
      lore: "&fHiện tại: %status%"
      command: "paymenttoggle"
      default: true
    team_chat:
      slot: 31
      material: "BELL"
      display-name: "&#08FB7Bᴄʜᴀᴛ ᴛᴇᴀᴍ"
      lore: "&fHiện tại: %status%"
      command: "teamchattoggle"
      default: true
    worth_display:
      slot: 32
      material: "LIME_CANDLE"
      display-name: "&#08FB7BʜɪệN ɢɪá ᴛʀị ɪᴛᴇᴍ"
      lore: "&fHiện tại: %status%"
      command: "worthtoggle"
      default: true
    after_duel_songs:
      slot: 33
      material: "JUKEBOX"
      display-name: "&#08FB7Bɴʜạᴄ sᴀᴜ ᴅᴜᴇʟ"
      lore: "&fHiện tại: %status%"
      command: "duelsongtoggle"
      default: true

sound:
  menu-click: "UI_BUTTON_CLICK"
  settings-reload: "ENTITY_PLAYER_LEVELUP"
  no-permission: "ENTITY_VILLAGER_NO"
  you-must-wait: "ENTITY_VILLAGER_NO"
